name: uno_todo_app
description: Todo App

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  lottie: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lotties/

#  fonts:
#    - family: Schyler
#      fonts:
#         - asset: assets/fonts/Schyler-Regular.ttf

