const uzUz = {
  "welcome": "\nUno To Do'ga xush kelibsiz!",
  "start": "Eng yaxshi To Do ilovasidan foydalanishni boshlang",
  "get_started": "Boshlash",
  "important":  "Muhim",
  "tasks": "Vazifalar",
  "new_list": "Yangi ro'yxat",
  "enter_list_title": "Ro'yxat sarlavhasini kiriting",
  "create": "Yaratmoq",
  "cancel": "Bekor qilish",
  "todo": "Qilmoq",
  "completed": "Bajarildi",
  "loading": "Yuklanmoqda...",
  "add_task": "Vazifa qo'shish",
  "rename_list": "Ro'yxat nomini o'zgartirish",
  "rename": "Nomini o'zgartirish",
  "search": "Qidirmoq",
  "delete": "O'chirish",
  "are_you_sure": "Ishonchingiz komilmi?,",
  "list_deleted": "Ro'yxat butunlay o'chiriladi",
  "important_tasks":"Muhim vazifalar",
  "try_starring": 'Bu yerda koʻrish uchun baʼzi vazifalarni belgilab koʻring.',
  "search_for_task": "Vazifalarni qidirish",
  "would_you_like": "Qanday vazifani topmoqchisiz?",
  "task_not_found": "Vazifa topilmadi",
  "could_not_find": "Biz baland va pastdan qidirdik, lekin\nizlagan narsangizni topa olmadik",
  "settings": "Sozlamalar",
  "general": "Umumiy",
  "purple": "Siyohrang",
  "blue": "ko'k",
  "yellow": "sariq",
  "color_palette": "Ranglar palitrasi",
  "language": "Til",
  "english": "ingliz",
  "russian": "ruscha",
  "uzbek":  "O'zbek",
  "change_restart": "O'zgartirish keyingi ilovani qayta ishga tushirishda qo'llaniladi",
  "mode":  "Rejim",
  "light":"Nur",
  "dark": "qorong'i",
  "about": "haqida",
  "version": "Versiya",
  "sign_out": "Chiqish",
  "sign_in": "Tizimga kirish",
  "sign_up": "Ro'yxatdan o'tish",
  "would_like_to_sign_out": "Chiqishni xohlayotganingizga ishonchingiz komilmi?",
  "due":"Muddati",
  "today": "Bugun",
  "tomorrow": "Ertaga",
  "next_week": "Keyingi hafta",
  "pick_date":  "Sana tanlang,",
  "task_name":  "Vazifa nomi",
  "completed_today": "Bugun yakunlandi",
  "note": "Eslatma",
};